definitions:
  main.Macro:
    properties:
      caption:
        type: string
      edit_url:
        type: string
      id:
        type: integer
      image:
        type: string
      original_text:
        type: string
      tags:
        items:
          type: string
        type: array
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: Shows all macros by keyword. Searches captions, original_text,
        and tags
      parameters:
      - description: Keyword
        in: path
        name: keyword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Search macros
swagger: "2.0"
